version: '3.8'
services:
  hybrid:
    image: node:lts-slim
    working_dir: /src
    ports:
      - 5555:5555
    volumes:
      - ./:/src
    command: yarn dev
    stdin_open: true
  pre-preview:
    image: node:lts-slim
    working_dir: /src
    volumes:
      - ./:/src
    command: yarn build
    profiles:
      - preview
  preview:
    build:
      dockerfile: Dockerfile.preview
    working_dir: /usr/share/nginx/html
    ports:
      - 5050:80
      - 5678:443
    volumes:
      - ./dist:/usr/share/nginx/html
    profiles:
      - preview
    depends_on:
      - pre-preview
